create table warehouses (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(100) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_warehouses_code unique (code)
);

create table locations (
    id bigint generated by default as identity primary key,
    warehouse_id bigint not null,
    code varchar(50) not null,
    name varchar(100) not null,
    zone varchar(50),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_locations_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint uk_locations_warehouse_code unique (warehouse_id, code)
);

create table skus (
    id bigint generated by default as identity primary key,
    code varchar(80) not null,
    name varchar(150) not null,
    barcode varchar(100),
    unit varchar(20) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_skus_code unique (code),
    constraint uk_skus_barcode unique (barcode)
);

create table inventories (
    id bigint generated by default as identity primary key,
    warehouse_id bigint not null,
    location_id bigint not null,
    sku_id bigint not null,
    available_quantity integer not null,
    allocated_quantity integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_inventories_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint fk_inventories_location foreign key (location_id) references locations (id),
    constraint fk_inventories_sku foreign key (sku_id) references skus (id),
    constraint uk_inventories_location_sku unique (location_id, sku_id),
    constraint ck_inventories_available_quantity check (available_quantity >= 0),
    constraint ck_inventories_allocated_quantity check (allocated_quantity >= 0)
);

create table outbound_waves (
    id bigint generated by default as identity primary key,
    wave_no varchar(50) not null,
    warehouse_id bigint not null,
    status varchar(30) not null,
    requested_by varchar(100) not null,
    memo varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_outbound_waves_wave_no unique (wave_no),
    constraint fk_outbound_waves_warehouse foreign key (warehouse_id) references warehouses (id)
);

create table picking_tasks (
    id bigint generated by default as identity primary key,
    task_no varchar(50) not null,
    outbound_wave_id bigint not null,
    warehouse_id bigint not null,
    source_location_id bigint not null,
    sku_id bigint not null,
    status varchar(30) not null,
    requested_quantity integer not null,
    picked_quantity integer not null,
    assigned_worker varchar(100),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_picking_tasks_task_no unique (task_no),
    constraint fk_picking_tasks_wave foreign key (outbound_wave_id) references outbound_waves (id),
    constraint fk_picking_tasks_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint fk_picking_tasks_source_location foreign key (source_location_id) references locations (id),
    constraint fk_picking_tasks_sku foreign key (sku_id) references skus (id),
    constraint ck_picking_tasks_requested_quantity check (requested_quantity > 0),
    constraint ck_picking_tasks_picked_quantity check (picked_quantity >= 0)
);

create table print_jobs (
    id bigint generated by default as identity primary key,
    job_no varchar(50) not null,
    outbound_wave_id bigint,
    picking_task_id bigint,
    status varchar(30) not null,
    document_type varchar(30) not null,
    printer_name varchar(150),
    failure_reason varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_print_jobs_job_no unique (job_no),
    constraint fk_print_jobs_wave foreign key (outbound_wave_id) references outbound_waves (id),
    constraint fk_print_jobs_picking_task foreign key (picking_task_id) references picking_tasks (id)
);

create table agent_connections (
    id bigint generated by default as identity primary key,
    agent_id varchar(80) not null,
    agent_type varchar(30) not null,
    status varchar(30) not null,
    endpoint varchar(255),
    last_seen_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_agent_connections_agent_id unique (agent_id)
);

create index idx_locations_warehouse_id on locations (warehouse_id);
create index idx_inventories_warehouse_sku on inventories (warehouse_id, sku_id);
create index idx_outbound_waves_warehouse_status on outbound_waves (warehouse_id, status);
create index idx_picking_tasks_wave_status on picking_tasks (outbound_wave_id, status);
create index idx_print_jobs_status on print_jobs (status);
create index idx_agent_connections_type_status on agent_connections (agent_type, status);
