create table receiving_orders (
    id bigint generated by default as identity primary key,
    receiving_no varchar(50) not null,
    warehouse_id bigint not null,
    status varchar(30) not null,
    supplier_name varchar(150),
    requested_by varchar(100) not null,
    memo varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_receiving_orders_receiving_no unique (receiving_no),
    constraint fk_receiving_orders_warehouse foreign key (warehouse_id) references warehouses (id)
);

create table receiving_order_lines (
    id bigint generated by default as identity primary key,
    receiving_order_id bigint not null,
    line_no integer not null,
    sku_id bigint not null,
    requested_quantity integer not null,
    received_quantity integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_receiving_order_lines_order foreign key (receiving_order_id) references receiving_orders (id),
    constraint fk_receiving_order_lines_sku foreign key (sku_id) references skus (id),
    constraint uk_receiving_order_lines_order_line unique (receiving_order_id, line_no),
    constraint ck_receiving_order_lines_requested_quantity check (requested_quantity > 0),
    constraint ck_receiving_order_lines_received_quantity check (received_quantity >= 0)
);

create table putaway_tasks (
    id bigint generated by default as identity primary key,
    task_no varchar(50) not null,
    receiving_order_line_id bigint not null,
    warehouse_id bigint not null,
    target_location_id bigint not null,
    sku_id bigint not null,
    status varchar(30) not null,
    putaway_quantity integer not null,
    assigned_worker varchar(100),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_putaway_tasks_task_no unique (task_no),
    constraint fk_putaway_tasks_receiving_line foreign key (receiving_order_line_id) references receiving_order_lines (id),
    constraint fk_putaway_tasks_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint fk_putaway_tasks_target_location foreign key (target_location_id) references locations (id),
    constraint fk_putaway_tasks_sku foreign key (sku_id) references skus (id),
    constraint ck_putaway_tasks_putaway_quantity check (putaway_quantity > 0)
);

create index idx_receiving_orders_warehouse_status on receiving_orders (warehouse_id, status);
create index idx_receiving_order_lines_order on receiving_order_lines (receiving_order_id);
create index idx_putaway_tasks_receiving_line_status on putaway_tasks (receiving_order_line_id, status);
create index idx_putaway_tasks_warehouse_status on putaway_tasks (warehouse_id, status);
