create table client_companies (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    name varchar(150) not null,
    business_registration_no varchar(50),
    contact_name varchar(100),
    contact_email varchar(150),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_client_companies_code unique (code),
    constraint uk_client_companies_business_registration_no unique (business_registration_no)
);

alter table skus add column client_company_id bigint not null;
alter table inventories add column client_company_id bigint not null;
alter table receiving_orders add column client_company_id bigint not null;
alter table outbound_waves add column client_company_id bigint not null;

alter table skus
    add constraint fk_skus_client_company foreign key (client_company_id) references client_companies (id);

alter table inventories
    add constraint fk_inventories_client_company foreign key (client_company_id) references client_companies (id);

alter table receiving_orders
    add constraint fk_receiving_orders_client_company foreign key (client_company_id) references client_companies (id);

alter table outbound_waves
    add constraint fk_outbound_waves_client_company foreign key (client_company_id) references client_companies (id);

alter table skus drop constraint uk_skus_code;
alter table skus drop constraint uk_skus_barcode;
alter table inventories drop constraint uk_inventories_location_sku;

alter table skus
    add constraint uk_skus_client_code unique (client_company_id, code);

alter table skus
    add constraint uk_skus_client_barcode unique (client_company_id, barcode);

alter table inventories
    add constraint uk_inventories_client_location_sku unique (client_company_id, location_id, sku_id);

create index idx_skus_client_company_id on skus (client_company_id);
create index idx_inventories_client_warehouse_sku on inventories (client_company_id, warehouse_id, sku_id);
create index idx_receiving_orders_client_status on receiving_orders (client_company_id, status);
create index idx_outbound_waves_client_status on outbound_waves (client_company_id, status);
