create table outbound_orders (
    id bigint generated by default as identity primary key,
    client_company_id bigint not null,
    warehouse_id bigint not null,
    outbound_order_no varchar(50) not null,
    external_reference_no varchar(100),
    intake_source varchar(30) not null,
    status varchar(30) not null,
    receiver_name varchar(100) not null,
    receiver_phone varchar(50) not null,
    zip_code varchar(20) not null,
    address1 varchar(255) not null,
    address2 varchar(255),
    delivery_memo varchar(500),
    requested_ship_date date,
    ordered_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_outbound_orders_client_order_no unique (client_company_id, outbound_order_no),
    constraint fk_outbound_orders_client_company foreign key (client_company_id) references client_companies (id),
    constraint fk_outbound_orders_warehouse foreign key (warehouse_id) references warehouses (id)
);

create table outbound_order_lines (
    id bigint generated by default as identity primary key,
    outbound_order_id bigint not null,
    line_no integer not null,
    sku_id bigint not null,
    ordered_quantity integer not null,
    allocated_quantity integer not null,
    picked_quantity integer not null,
    packed_quantity integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_outbound_order_lines_order foreign key (outbound_order_id) references outbound_orders (id),
    constraint fk_outbound_order_lines_sku foreign key (sku_id) references skus (id),
    constraint uk_outbound_order_lines_order_line unique (outbound_order_id, line_no),
    constraint ck_outbound_order_lines_ordered_quantity check (ordered_quantity > 0),
    constraint ck_outbound_order_lines_allocated_quantity check (allocated_quantity >= 0),
    constraint ck_outbound_order_lines_picked_quantity check (picked_quantity >= 0),
    constraint ck_outbound_order_lines_packed_quantity check (packed_quantity >= 0)
);

alter table picking_tasks add column outbound_order_line_id bigint;

alter table picking_tasks
    add constraint fk_picking_tasks_outbound_order_line
    foreign key (outbound_order_line_id) references outbound_order_lines (id);

create index idx_outbound_orders_client_status on outbound_orders (client_company_id, status);
create index idx_outbound_orders_warehouse_status on outbound_orders (warehouse_id, status);
create index idx_outbound_order_lines_order on outbound_order_lines (outbound_order_id);
create index idx_picking_tasks_order_line on picking_tasks (outbound_order_line_id);
