create table outbound_order_line_allocations (
    id bigint generated by default as identity primary key,
    outbound_order_line_id bigint not null,
    inventory_id bigint not null,
    location_id bigint not null,
    sku_id bigint not null,
    allocated_quantity integer not null,
    picked_quantity integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_outbound_allocations_order_line foreign key (outbound_order_line_id) references outbound_order_lines (id),
    constraint fk_outbound_allocations_inventory foreign key (inventory_id) references inventories (id),
    constraint fk_outbound_allocations_location foreign key (location_id) references locations (id),
    constraint fk_outbound_allocations_sku foreign key (sku_id) references skus (id),
    constraint ck_outbound_allocations_allocated_quantity check (allocated_quantity > 0),
    constraint ck_outbound_allocations_picked_quantity check (picked_quantity >= 0)
);

create index idx_outbound_allocations_order_line on outbound_order_line_allocations (outbound_order_line_id);
create index idx_outbound_allocations_inventory on outbound_order_line_allocations (inventory_id);
